# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

r:
  - oldrel
  - release

dist: trusty

branches:
  only:
    - feature/ci

# set up postgres
services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - createdb rpglt_empty
  - psql -d rpglt_empty -c "create extension postgis;"
  - createdb rpglt_data
  - psql -d rpglt_data -c "create extension postgis;"
  - psql -d rpglt_data -c "create schema example_data;"
  - gzip -dc ./sql/example_data.sql.gz | psql -d rpglt_data

after_success:
  - dropdb rpglt_empty
  - dropdb rpglt_data

