# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  - ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\9.5\bin;%PATH%

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here
services:
  - postgresql95

build_script:
  - travis-tool.sh install_deps
  - createdb rpglt_empty
  - psql -d rpglt_empty -c "create extension postgis;"
  - createdb rpglt_data
  - psql -d rpglt_data -c "create extension postgis;"
  - psql -d rpglt_data -c "create schema example_data;"
  - 7z x .\inst\sql\example_data.sql.gz -so | psql -d rpglt_data

test_script:
  - travis-tool.sh run_tests

branches:
  only:
    - dev

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
